<nav class="main-nav">
        <ul class="main-nav">
            <li class="main-nav"><a href="index.php">Index</a></li>
            <li class="main-nav"><a href="product.php">Product</a></li>
            <li class="main-nav"><a href="enquiry.php">Enquire</a></li>
            <li class="main-nav"><a href="about.php">About</a></li>
            <li class="main-nav"><a href="enhancements.php">Enhancements</a></li>
        </ul>
</nav>
