<nav class="main-nav">
        <ul class="main-nav">
            <li class="main-"><a href="main-nav.html">Index</a></li>
            <li class="main-nav"><a href="product.html">Product</a></li>
            <li class="main-nav"><a href="enquiry.html">Enquire</a></li>
            <li class="main-nav"><a href="about.html">About</a></li>
            <li class="main-nav"><a href="enhancements.html">Enhancements</a></li>
        </ul>
</nav>
